### ISSUE TITLE
mac ci failure when running installed app

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#1145]
In https://github.com/brimsec/brim/pull/1138, I needed to disable the part of the mac ci tests that builds & installs Brim, and runs the integration tests against the installed app:
https://github.com/brimsec/brim/pull/1138/commits/412856bf83e02633b30195d1b47171610786c4f3

I couldn't repro the failure locally on my mac, using the built brim from the brim/dist directory or by building & installing. This issue tracks re-enabling the build & install step of the mac integration test & tracking down why using that fails in testing.

**Comment by philrz** [comment]
Last weekend I had some spare time and wanted to witness a repro of this, hence I'm sharing the data here for what that's worth. I made a branch `mac-ci-fail` where I re-enabled the part of the Mac CI that installed Brim, then triggered it to run ten times in a row. Out of those ten, it failed two times in a row, both at the same place with the same symptom, that being an `ECONNRESET` when running the "histogram deep inspection", which is the first integration test out of the gate. An example of the failure output from https://github.com/brimsec/brim/runs/1269607527:

```
2020-10-17T22:40:12.3164710Z [2020-10-17 22:40:12.215 info]: Running test: histogram deep inspection
2020-10-17T22:40:21.1642230Z [2020-10-17 22:40:21.037 error]: handleError: Test hit exception: connect ECONNRESET 127.0.0.1:9515
2020-10-17T22:40:21.1646670Z [2020-10-17 22:40:21.037 info]: handleError: Looking for any desktop app notifications
2020-10-17T22:40:21.1648480Z [2020-10-17 22:40:21.038 info]: handleError: desktop app notification not found
2020-10-17T22:40:24.0211650Z [2020-10-17 22:40:23.915 info]: wrote out screen shot to "/var/tmp/brimsec/itest/failure-601ba20b.png"
2020-10-17T22:40:25.2604860Z FAIL itest/tests/histogram.test.ts (32.543s)
2020-10-17T22:40:25.2608400Z   Histogram tests
2020-10-17T22:40:25.2613010Z     ✕ histogram deep inspection (28836ms)
2020-10-17T22:40:25.2613350Z 
2020-10-17T22:40:25.2614120Z   ● Histogram tests › histogram deep inspection
2020-10-17T22:40:25.2614480Z 
2020-10-17T22:40:25.2614890Z     RequestError: connect ECONNRESET 127.0.0.1:9515
2020-10-17T22:40:25.2615300Z 
2020-10-17T22:40:25.2615950Z       at ClientRequest.<anonymous> (../node_modules/webdriver/node_modules/got/dist/source/core/index.js:957:25)
2020-10-17T22:40:25.2617470Z       at ClientRequest.origin.emit (../node_modules/webdriver/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
```

When I have more time to tinker with this, one thought I've had would be to look at narrowing the scope to cover just this one test and start `tcpdump` before running it so I could compare the content/timing of packets seen on localhost before/at the moment when this reset is sent.

**Comment by philrz** [comment]
Update: After noticing this is still commented out, but we've made a bunch of other improvements to our Brim CI of late, I figured it was worth uncommenting this and giving it another go, which I just did in a current branch `mac-ci-fail-feb2021`. Alas, after one successful run, it failed on the second run at the same `Histogram tests › histogram deep inspection` test where it failed before. Sigh!
