### ISSUE TITLE
Stack dump when doing "Whois" lookup in Log Detail window

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#1362]
Repro is with Brim commit `91cdd34`.

In the video below, I've imported test pcap https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz (after uncompressing) and entered the Z search `filename=aslugworth`. If click the top `files` event in the Log Detail side panel and right-click to look up its `tx_hosts` value in Whois, it works fine. However, if I pop the same event out into a standalone window, and do the right-click Whois lookup, I get a stack dump.

https://user-images.githubusercontent.com/5934157/104955032-57e04900-597e-11eb-8c27-9a8273441fe1.mov

The dump contents:

```
Error: Objects are not valid as a React child (found: object with keys {type, value}). If you meant to render a collection of children, use an array instead.
    in span (created by ModalDialog)
    in div (created by styled.div)
    in styled.div (created by ModalDialog)
    in div (created by styled.div)
    in styled.div (created by ModalDialog)
    in Transition (created by CSSTransition)
    in CSSTransition (created by ModalDialog)
    in div (created by styled.div)
    in styled.div (created by ModalDialog)
    in ModalDialog (created by Modals)
    in Modals
    in ThemeProvider
    in Provider
    in AppErrorBoundary
    at throwOnInvalidObjectType (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:13413:15)
    at createChild (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:13651:7)
    at reconcileChildrenArray (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:13900:25)
    at reconcileChildFibers (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:14305:14)
    at reconcileChildren (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:16762:28)
    at updateHostComponent (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:17302:3)
    at beginWork (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:18627:14)
    at HTMLUnknownElement.callCallback (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:237:16)
    at invokeGuardedCallback (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:292:31)
```

**Comment by philrz** [comment]
Verified in Brim commit `47166dd`.

Repeating the original repro steps as shown in the attached video, now I can bring up Whois in the Log Detail window without triggering a stack dump.

https://user-images.githubusercontent.com/5934157/107281232-4256c000-6a0e-11eb-89c7-0595ab969d6d.mp4

Thanks @mason-fish!
