### ISSUE TITLE
master starts to error screen with existing space 

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#584]
If I try to run Brim off of current master (16e606a7) when I've previously created a space with the Brim 0.6.0 release, the application loads directly to an error screen, with this error:

```
TypeError: Invalid attempt to spread non-iterable instance
    at _nonIterableSpread (/Users/alfred/work/brim/dist/js/state/LogDetails/reducer.js:15:39)
    at _toConsumableArray (/Users/alfred/work/brim/dist/js/state/LogDetails/reducer.js:13:95)
    at toHistory (/Users/alfred/work/brim/dist/js/state/LogDetails/reducer.js:83:43)
    at /Users/alfred/work/brim/dist/js/state/LogDetails/selectors.js:32:33
    at /Users/alfred/work/brim/node_modules/reselect/lib/index.js:76:25
    at /Users/alfred/work/brim/node_modules/reselect/lib/index.js:36:25
    at /Users/alfred/work/brim/node_modules/reselect/lib/index.js:90:33
    at Object.getHistory (/Users/alfred/work/brim/node_modules/reselect/lib/index.js:36:25)
    at Function.stateToProps [as mapToProps] (/Users/alfred/work/brim/dist/js/components/RightPane.js:172:40)
    at mapToPropsProxy (/Users/alfred/work/brim/node_modules/react-redux/lib/connect/wrapMapToProps.js:53:92)
```

repro on windows & mac:
* run 0.6.0 release, ingest a pcap, exit brim
* run master (currently at 16e606a7)

**Comment by philrz** [comment]
Verified in Brim commit `b15bf1b8` talking to `zqd` commit `87135a9`. Now after I've ingested a pcap into `v0.6.0`, exited Brim, and restarted at commit `b15bf1b8`, I no longer see an error.

![image.png](https://images.zenhubusercontent.com/5e40bbae92d04e424a90e56f/c97c8966-fc78-42fd-b02f-0e99859d04df)

Thanks @jameskerr!
