### ISSUE TITLE
Crash when revisiting tab for deleted Space where a pcap had been opened

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#652]
Repro is on Brim GA tagged `v0.8.0`. Steps when starting from a fresh environment:

1. Load a pcap file into the first tab
2. Click the shark icon to open a flow from the pcap
3. Quit Wireshark
4. Open a new tab and click the Trash icon to delete the Space
5. Click back to the first tab and see this crash:

```
TypeError: Cannot read property 'packet_support' of undefined
    at PacketsButton (/Applications/Brim.app/Contents/Resources/app/dist/js/components/PacketsButton.js:53:56)
    at renderWithHooks (/Applications/Brim.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:16260:18)
    at mountIndeterminateComponent (/Applications/Brim.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:18794:13)
    at beginWork$1 (/Applications/Brim.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:20162:16)
    at HTMLUnknownElement.callCallback (/Applications/Brim.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:336:14)
    at Object.invokeGuardedCallbackDev (/Applications/Brim.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:385:16)
    at invokeGuardedCallback (/Applications/Brim.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:440:31)
    at beginWork$$1 (/Applications/Brim.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:25780:7)
    at performUnitOfWork (/Applications/Brim.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:24698:12)
    at workLoopSync (/Applications/Brim.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:24671:22)
```

Here's a repro video and the small pcap I used in it:

[Repro.zip](https://github.com/brimsec/brim/files/4505182/Repro.zip)
[hello.pcapng.zip](https://github.com/brimsec/brim/files/4505248/hello.pcapng.zip)

**Comment by philrz** [comment]
Verified in Brim commit `f837314` talking to `zqd` commit `0e6240b`. Per the attached video, repeating the original repro steps, the app no longer crashes. Instead when going back to the first tab we see the expected message about the Space having been deleted.

[Verify.mov.zip](https://github.com/brimsec/brim/files/4546820/Verify.mov.zip)

Thanks @jameskerr!
