### ISSUE TITLE
deflake menu clicks

### ISSUE THREAD

**Issue by mikesbrown** [brimsec/brim#668]
Sometimes an element, especially one in a menu, cannot be clicked.
```
 Query tests › query004: "* | every 2s count() | sort ts"

    element click intercepted: Element <li>...</li> is not clickable at point (867, 98). Other element would receive the click: <ul data-test-locator="span_menu">...</ul>

      at new RuntimeError (../node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
      at Request._callback (../node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
      at Request.self.callback (../node_modules/request/request.js:185:22)
      at Request.<anonymous> (../node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (../node_modules/request/request.js:1083:12)
```
I believe we are trying to click on the element while it is still being animated.

While we are [constrained to using WebdriverIO v4](https://github.com/electron-userland/spectron/issues/349) without any sort of notion of `isClickable()`, WebdriverIO v5 has an [`isClickable()`](https://v5.webdriver.io/docs/api/element/isClickable.html). We might be able to write our own. We could also do better about retrying clicks.

**Comment by mikesbrown** [comment]
Reproduction is difficult, which means work to verify a fix is difficult. I was able to trigger a few test failures by triggering 4 CI jobs roughly concurrently. One of the jobs had 2 test failures.
