### ISSUE TITLE
Clicking Data Directory "Choose" button in relaunched app causes it to hang

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#810]
Repro is in Brim commit `dc488b1`. I originally encountered this in dev mode but then reproduced it in a release artifact based on this same commit as well.

Repro steps are:

1. Start from a fresh, first-time-ever launch of the app. I've done nothing in the app.
2. Quit the app
3. Relaunch the app
4. Enter the **Preferences** menu, and next to **Data Directory**, click the **Choose** button

At this point the main app window goes white and is completely hung. No amount of Reset State, Reload, etc. seems to unstick it. In dev mode, of course I could Control-C my `npm start`, but with the release artifact I had to go into Activity Monitor and "Force Quit" the app, which seems pretty bad.

At the moment it hangs, the message in my `npm` window:

```
Error occurred in handler for 'windows:initialState': TypeError: Cannot read property 'state' of undefined
    at /Users/phil/work/brim/dist/js/electron/ipc/windows/mainHandler.js:32:19
    at electron/js2c/browser_init.js:1093:52
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3840:43)
    at WebContents.emit (events.js:203:13)
```

[Repro.zip](https://github.com/brimsec/brim/files/4670283/Repro.zip)

**Comment by philrz** [comment]
Verified with a Brim release artifact based on commit `c1dbca6`. Per the attached video, when I repeat the original repro steps, now when I re-launch the app and click the "Choose" button in the Preferences screen, there's no more "white window" crash.

[Verify.mov.zip](https://github.com/brimsec/brim/files/4684575/Verify.mov.zip)

Thanks @mason-fish!
